apiVersion: apps/v1 
kind: Deployment
metadata:
  name: leaderboard-api-deployment
spec:
  selector:
    matchLabels:
      app: leaderboard-api
  replicas: 1
  template:
    metadata:
      labels:
        app: leaderboard-api
    spec:
      containers:
      - name: leaderboard-api
        image: gcr.io/ccarse/leaderboard-api
        ports:
        - containerPort: 1337
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: leaderboard-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1337
  selector:
    app: leaderboard-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leaderboard-api
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - codycar.se
    secretName: tls-secret
  rules:
  - host: codycar.se
    http:
      paths:
      - pathType: Prefix
        path: /leaderboard-api
        backend:
          service: 
            name: leaderboard-api
            port: 
              number: 80
  # defaultBackend:
  #   service: 
  #     name: leaderboard-api
  #     port: 
  #       number: 80
