apiVersion: apps/v1 
kind: Deployment
metadata:
  name: leaderboard-api-deployment
spec:
  selector:
    matchLabels:
      app: leaderboard-api
  replicas: 1
  template:
    metadata:
      labels:
        app: leaderboard-api
    spec:
      containers:
      - name: leaderboard-api
        image: gcr.io/ccarse/leaderboard-api
        ports:
        - containerPort: 1337
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: leaderboard-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1337
  selector:
    app: leaderboard-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: leaderboard-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - codycar.se
    secretName: tls-secret
  rules:
  - host: codycar.se
    http:
      paths:
      - path: /leaderboard-api
        backend:
          serviceName: leaderboard-api
          servicePort: 80
